const queries = {};

queries.infoPopup = `SELECT NOMBRE, EMAIL, TLF, URL, DIR.TIPO_VIA, DIR.NOMBRE_VIA, DIR.NUMERO, L.FOTO  FROM USERS
JOIN (SELECT ID_USER,TIPO_VIA, NOMBRE_VIA, NUMERO FROM DIRECCIONES) AS DIR ON USERS.ID = DIR.ID_USER 
JOIN (SELECT ID_USER, LOGO_NOMBRE AS FOTO FROM LOGO) AS L ON USERS.ID = L.ID_USER WHERE USERS.ID  = ?`;

module.exports = queries;
