export const initialValues={
    NOMBRE:"",
    EMAIL:"",
    TLF:"",
    URL:"",
    DESCRIPCION:"",
    PASSWORD:"",
    repetirPassword:"",
    sector:"",
    CATEGORIA:"",
    DIRECCIONES:[{TIPO_VIA:"",
    NOMBRE_VIA:"",
    NUMERO:"",
    PISO:"",
    PUERTA:"",
    BLOQUE:"",
    CP:"",
    LOCALIDAD:"",
    PROVINCIA:"",
    PAIS:"",
    LONGITUD:"",
    LATITUD:""}],
    
}