export const initialValues={
    nombre:"",
    email:"",
    tfn:"",
    url:"",
    descripcion:"",
    password:"",
    repetirPassword:"",
    sector:"",
    categoria:"",
    direcciones:[{tipoVia:"",
    nombreVia:"",
    numero:"",
    piso:"",
    puerta:"",
    bloque:"",
    CP:"",
    localidad:"",
    provincia:"",
    pais:"",
    longitud:"",
    latitud:""}],
    
}